# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

# Out-of-memory
# https://stackoverflow.com/questions/60548011
options:
  docker: true
  size: 2x

pipelines:
  default:
    - step:
        size: 2x
        name: "Build docker image"
        image: atlassian/default-image:2
        services:
          - docker
        caches:
          - docker
        script: 
          - export BACKEND_IMAGE_NAME=${DOCKER_HUB_USERNAME}/tgrains-cropmodel-backend
          - docker build -t $BACKEND_IMAGE_NAME:$BITBUCKET_COMMIT -t $BACKEND_IMAGE_NAME:latest ./server/
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push $BACKEND_IMAGE_NAME

definitions:
  services:
    docker:
      memory: 4096