version: '3.6'

services: 
  gunicorn:
    container_name: gunicorn
    build:
      context: ./server
    restart: unless-stopped
    volumes:
      # You don't need this for production because the Dockerfile
      # does COPY . /app, but it helps for development!
      - "${PWD}/server/:/app"
    expose:
      - 5000

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - gunicorn
    restart: unless-stopped
    ports:
        - 80:80
    volumes:
        - "${PWD}/conf/subsite.conf:/etc/nginx/conf.d/default.conf:ro"
        - "${PWD}/frontend:/var/www/html"
