services:
  gunicorn:
    image: samfinnigan/tgrains-cropmodel-backend:latest
    container_name: ${COMPOSE_PROJECT_NAME}_gunicorn
    restart: unless-stopped
    command: gunicorn --worker-tmp-dir=/dev/shm --workers=2 --threads=4 --worker-class=gthread --timeout=120 --log-level INFO --log-file=- --bind=0.0.0.0:5000 server:app
    environment:
      - FLASK_ENV=development
      - REDIS_URL=${REDIS_URL}
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:devpassword@mariadb/${MYSQL_DATABASE}
      - BAU_PRECALC_RUNS=16
      - BAU_PRECALC_TIMEOUT=600
      - LOG_LEVEL=INFO
      - SCRIPT_NAME=/api
      - PROXY_FIX=1 # Behind traefik, set this to 2
    expose:
      - 5000
    networks:
      - backend

# Run as docker-compose up -d --scale celery=8
# We can't use the multithreading inside Celery because the DLL isn't threadsafe!!
  celery:
    image: samfinnigan/tgrains-cropmodel-backend:latest
    #container_name: ${COMPOSE_PROJECT_NAME}_celery
    restart: unless-stopped
    command: celery -A tasks.celery worker --loglevel=INFO --concurrency=1 -- worker.prefetch_multiplier=1
    working_dir: /app/
    environment:
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
    networks:
      - backend

  mariadb:
    image: mariadb
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    ports:
      # For development, expose mariadb to host
      - "3306:3306/tcp"
    networks:
      - backend
    volumes:
      - mariadb:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - backend
    ports:
      # For development, expose redis to host
      - "6379:6379/tcp"
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf

  frontend:
    image: samfinnigan/tgrains-cropmodel-frontend
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: unless-stopped
    ports:
      # For development, expose frontend to host
      - "8000:80/tcp"
    networks:
      - backend
      - default
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webs_traefik"
      - "traefik.http.routers.cropmodel-http.entrypoints=http"
      - "traefik.http.routers.cropmodel-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.cropmodel-http.middlewares=httpsRedirect@file"
      - "traefik.http.routers.cropmodel.entrypoints=https"
      - "traefik.http.routers.cropmodel.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.cropmodel.tls=true"
      - "traefik.http.routers.cropmodel.tls.certresolver=letsencrypt"
      - "traefik.http.services.cropmodel.loadbalancer.server.port=80"
      - "traefik.http.middlewares.forwardPortHeader.headers.customrequestheaders.X-Forwarded-Port=443"
      - "traefik.http.routers.test.middlewares=secured@file,forwardPortHeader@docker"

networks:
  backend:
  default:
  external:
    name: webs_traefik

volumes:
  mariadb:
