version: '3.6'

services:
  gunicorn:
    image: samfinnigan/tgrains-cropmodel-backend:latest
    container_name: ${COMPOSE_PROJECT_NAME}_gunicorn
    restart: unless-stopped
    command: gunicorn --worker-tmp-dir=/dev/shm --workers=2 --threads=4 --worker-class=gthread --timeout=120 --log-level INFO --log-file=- --bind=0.0.0.0:5000 server:app
    depends_on:
      - redis
      - celery
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=mysql://root:devpassword@mariadb/tgrains
      - BAU_PRECALC_RUNS=16
      - BAU_PRECALC_TIMEOUT=600
      - LOG_LEVEL=INFO
    expose:
      - 5000
    networks:
      - backend

# Run as docker-compose up -d --scale celery=8
# We can't use the multithreading inside Celery because the DLL isn't threadsafe!!
  celery:
    image: samfinnigan/tgrains-cropmodel-backend:latest
    #container_name: ${COMPOSE_PROJECT_NAME}_celery
    restart: unless-stopped
    command: celery -A tasks.celery worker --loglevel=INFO --concurrency=1 -- worker.prefetch_multiplier=1
    working_dir: /app/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - backend

  mariadb:
    image: mariadb
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=devpassword
      - MYSQL_DATABASE=tgrains
      - MYSQL_USER=flask
      - MYSQL_PASSWORD=sqlalchemy_devpassword
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    ports:
      # For development, expose mariadb to host
      - "3306:3306/tcp"
    networks:
      - backend
    volumes:
      - mariadb:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: unless-stopped
    networks:
      - backend
    ports:
      # For development, expose redis to host
      - "6379:6379/tcp"

  frontend:
    image: samfinnigan/tgrains-cropmodel-frontend
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: unless-stopped
    depends_on:
      - gunicorn
    ports:
      # For development, expose frontend to host
      - "8000:80/tcp"
    networks:
      - backend
      - default
      - external
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webs_traefik"
      - "traefik.http.routers.cropmodel-http.entrypoints=http"
      - "traefik.http.routers.cropmodel-http.rule=Host(`model.tgrains.com`)"
      - "traefik.http.routers.cropmodel-http.middlewares=httpsRedirect@file"
      - "traefik.http.routers.cropmodel.entrypoints=https"
      - "traefik.http.routers.cropmodel.rule=Host(`model.tgrains.com`)"
      - "traefik.http.routers.cropmodel.tls=true"
      - "traefik.http.routers.cropmodel.tls.certresolver=letsencrypt"
      - "traefik.http.routers.cropmodel.middlewares=secured@file"
      - "traefik.http.services.cropmodel.loadbalancer.server.port=80"

networks:
  backend:
  default:
  external:
    name: webs_traefik

volumes:
  mariadb:
