name: tgrains
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cppyy
  - flask
  - markdown
  - gunicorn
  - celery=5.0.5
  - click=7.1.2
  - redis
  - redis-py
  - flask-redis
  - sqlalchemy=1.3.18
  - flask-sqlalchemy
  - mysqlclient
