name: tgrains
channels:
  - conda-forge
dependencies:
  - celery=5.4
  - cppyy=3.5.0
  - flask-redis=0.4.0
  - flask-sqlalchemy=2.5.1
  - flask=2.2.5
  - gunicorn=23.0
  - markdown=3.10.1
  - pymysql=1.1
  - python=3.12
  - redis-py=4.6
  - sqlalchemy=1.4
